### ISSUE TITLE
Unnecessary line break characters in some files

### ISSUE THREAD

**Issue by Raysphere24** [meteostat/weather-stations#455]
"10728.json" contains "\n" in the "name[en]" value ("Mannheim\n \/ Coleman").
"71211.json" contains "\n" in the "timezone" value ("America\/Vancouver\n").
These unnecessary line breaks may be troublesome in some cases.

**Comment by clampr** [comment]
Thanks for reporting. If anyone has time to remove those line breaks, help would be highly appreciated.
