### ISSUE TITLE
Meteostat forecast down ?

### ISSUE THREAD

**Issue by Meywether** [meteostat/weather-stations#467]
Dear Developers,
thanks for your great python api!

Is there any problem with the forecast api ? 
We try to get a result with following code:

![image](https://user-images.githubusercontent.com/39849054/129604831-b5aae7e2-e8aa-43d0-8680-d61fbfd0740b.png)

But it only works till 17.08.2021 08:00

Or are we doing something wrong ?

Best regards and many thanks 

Meywether

**Comment by clampr** [comment]
You're right. This was caused by a recent change and it's already resolved. The forecasts will be back within 1 to 2 days.

**Comment by Meywether** [comment]
@clampr Thanks for your quick response. Is the same happening to the bulk download ? 
https://bulk.meteostat.net/v2
Because there I get a 403 Error.

Thanks in advance

**Comment by clampr** [comment]
Try a specific file: https://bulk.meteostat.net/v2/hourly/full/10637.csv.gz

It should work.

**Comment by Meywether** [comment]
@clampr 
Sorry, I need to reopen this issue. It is since yesterday again stuck:
![image](https://user-images.githubusercontent.com/39849054/129850276-fde5feca-1a9f-4c70-9135-f3459e3a0315.png)

Cleaned cache an everything.
I requested exactly the same time period forecast (one week) as in the web tool, where it is working quite well.

Do you have any information on this ?

Kind regards
Meywether

**Comment by clampr** [comment]
I cleared the Cloudflare cache. Is it still happening?

**Comment by Meywether** [comment]
@clampr Works ! Thanks !
