### ISSUE TITLE
Station 72314 Location

### ISSUE THREAD

**Issue by ttymck** [meteostat/weather-stations#469]
Station 72314 (Charlotte Douglas Int'l) is listed at (35.2167, -80.1167) ([see here](https://meteostat.net/en/station/72314))

However, I believe it should be located at (35.214, -80.9431)[1]

The current coordinates are well to the east of Charlotte (~80km), I noticed this because I am unable to get historical normals for Charlotte, but the airport weather station has some data. I wanted to make sure I am not mistaken before submitting a PR. I am happy to submit corrections if this is correct (there are some other locations for which I am having the same issue, and I may be able to help correct those too).

Thanks!

[1] https://distancem.com/airports/airport-kclt

**Comment by clampr** [comment]
Hi Tyler,

You're a 100% right about that! I have no idea where the old coordinates are coming from, but they're definitely incorrect. Feel free to create a PR - I will merge it :wink:

Thanks!
