### ISSUE TITLE
Station 72232 - Boothville - Duplicate WMO ID

### ISSUE THREAD

**Issue by ttymck** [meteostat/weather-stations#471]
I was looking for Baton Rouge historical normals, and noticed that KBTR (Baton Rouge Metro Ryan Field) has the [WMO ID 72232](https://weather.gladstonefamily.net/site/KBTR). In Meteostat, this station is listed as Boothville, LA (ICAO: KBVE)

NOAA indicates that the WMO has an ID collision, and and Boothville used 72232 until March 2020:

![72232](https://user-images.githubusercontent.com/46075030/142517106-bdcefd1e-dcf6-473c-a92e-8cf7f2433a6b.PNG)

I wanted to ask if you are able to definitively confirm that Meteostat's 72232 is indeed Boothville, and if so, are we able to source and import KBTR station data? (I'd be happy to help)

**Comment by clampr** [comment]
I checked all the station IDs for Boothville and I can confirm that all data for `72232` refers to Boothville. We'll need to remove the entry under `identifiers.wmo` for `72232` (Boothville) and create a new station (with a new ID) for Baton Rouge. I'll take care of this in the next days.

Thanks for reporting!

**Comment by clampr** [comment]
Here it is: https://meteostat.net/en/station/KBTR0?t=2021-11-22/2021-11-22

More data will probably be available in the following weeks.

**Comment by ttymck** [comment]
Awesome! Thanks @clampr
